import type {Article, Sources} from "../components/ArticleCardComponent.tsx";

export const mockArticles: Article[] = [
    {
        id: "mock-data",
        title: "AI Revolution Changes Tech Industry",
        description: "Artificial Intelligence is transforming the way businesses operate worldwide.",
        content: "In-depth content about how AI tools are used across multiple industries...",
        url: "https://example.com/articles/1",
        urlToImage: "https://example.com/images/ai.jpg",
        publishedAt: "2025-06-26T12:34:56Z",
        source: {
            id: "bbc-news",
            name: "BBC News",
        },
        author: "John Doe",
        category: "technology",
    },
    {
        id: "mock-data",
        title: "Global Economy Faces New Challenges",
        description: "Experts warn about slowing economic growth amid geopolitical tensions.",
        content: "The global economy is experiencing uncertainties due to changing political landscapes...",
        url: "https://example.com/articles/2",
        urlToImage: "https://example.com/images/economy.jpg",
        publishedAt: "2025-06-25T09:15:30Z",
        source: {
            id: "cnn",
            name: "CNN",
        },
        author: "Jane Smith",
        category: "business",
    },
    {
        id: "mock-data",
        title: "Global Economy Faces New Challenges",
        description: "Experts warn about slowing economic growth amid geopolitical tensions.",
        content: "The global economy is experiencing uncertainties due to changing political landscapes...",
        url: "https://example.com/articles/2",
        urlToImage: "https://example.com/images/economy.jpg",
        publishedAt: "2025-06-25T09:15:30Z",
        source: {
            id: "cnn",
            name: "CNN",
        },
        author: "Jane Smith",
        category: "business",
    },
    {
        id: "mock-data",
        title: "Global Economy Faces New Challenges",
        description: "Experts warn about slowing economic growth amid geopolitical tensions.",
        content: "The global economy is experiencing uncertainties due to changing political landscapes...",
        url: "https://example.com/articles/2",
        urlToImage: "https://example.com/images/economy.jpg",
        publishedAt: "2025-06-25T09:15:30Z",
        source: {
            id: "cnn",
            name: "CNN",
        },
        author: "Jane Smith",
        category: "business",
    },
    {
        id: "mock-data",
        title: "Global Economy Faces New Challenges",
        description: "Experts warn about slowing economic growth amid geopolitical tensions.",
        content: "The global economy is experiencing uncertainties due to changing political landscapes...",
        url: "https://example.com/articles/2",
        urlToImage: "https://example.com/images/economy.jpg",
        publishedAt: "2025-06-25T09:15:30Z",
        source: {
            id: "cnn",
            name: "CNN",
        },
        author: "Jane Smith",
        category: "business",
    },
    {
        id: "mock-data",
        title: "Global Economy Faces New Challenges",
        description: "Experts warn about slowing economic growth amid geopolitical tensions.",
        content: "The global economy is experiencing uncertainties due to changing political landscapes...",
        url: "https://example.com/articles/2",
        urlToImage: "https://example.com/images/economy.jpg",
        publishedAt: "2025-06-25T09:15:30Z",
        source: {
            id: "cnn",
            name: "CNN",
        },
        author: "Jane Smith",
        category: "business",
    },
    {
        id: "mock-data",
        title: "Global Economy Faces New Challenges",
        description: "Experts warn about slowing economic growth amid geopolitical tensions.",
        content: "The global economy is experiencing uncertainties due to changing political landscapes...",
        url: "https://example.com/articles/2",
        urlToImage: "https://example.com/images/economy.jpg",
        publishedAt: "2025-06-25T09:15:30Z",
        source: {
            id: "cnn",
            name: "CNN",
        },
        author: "Jane Smith",
        category: "business",
    },
    {
        id: "mock-data",
        title: "Global Economy Faces New Challenges",
        description: "Experts warn about slowing economic growth amid geopolitical tensions.",
        content: "The global economy is experiencing uncertainties due to changing political landscapes...",
        url: "https://example.com/articles/2",
        urlToImage: "https://example.com/images/economy.jpg",
        publishedAt: "2025-06-25T09:15:30Z",
        source: {
            id: "cnn",
            name: "CNN",
        },
        author: "Jane Smith",
        category: "business",
    },
    {
        id: "mock-data",
        title: "Global Economy Faces New Challenges",
        description: "Experts warn about slowing economic growth amid geopolitical tensions.",
        content: "The global economy is experiencing uncertainties due to changing political landscapes...",
        url: "https://example.com/articles/2",
        urlToImage: "https://example.com/images/economy.jpg",
        publishedAt: "2025-06-25T09:15:30Z",
        source: {
            id: "cnn",
            name: "CNN",
        },
        author: "Jane Smith",
        category: "business",
    },
    {
        id: "mock-data",
        title: "Global Economy Faces New Challenges",
        description: "Experts warn about slowing economic growth amid geopolitical tensions.",
        content: "The global economy is experiencing uncertainties due to changing political landscapes...",
        url: "https://example.com/articles/2",
        urlToImage: "https://example.com/images/economy.jpg",
        publishedAt: "2025-06-25T09:15:30Z",
        source: {
            id: "cnn",
            name: "CNN",
        },
        author: "Jane Smith",
        category: "business",
    },
];


export const mockSources: Sources[] = [
    {
        id: "bbc-news",
        name: "BBC News",
        description: "Use BBC News for up-to-the-minute news, breaking news, video, audio and feature stories.",
        url: "http://www.bbc.co.uk/news",
        category: "general",
        language: "en",
        country: "gb",
    },
    {
        id: "cnn",
        name: "CNN",
        description: "View the latest news and breaking news today for U.S., world, weather, entertainment, politics and health.",
        url: "http://us.cnn.com",
        category: "general",
        language: "en",
        country: "us",
    },
    {
        id: "techcrunch",
        name: "TechCrunch",
        description: "Breaking technology news, analysis, and opinions from TechCrunch.",
        url: "https://techcrunch.com",
        category: "technology",
        language: "en",
        country: "us",
    }
];

